USE PI



INSERT INTO CURSO(NOMBRE, SIGLA, Descripcion)
VALUES ('ALGEBRA LINEAL', 'CI01', 'ESTE CURSO ENSEÑA SOBRE TRANSFORMACIONES LINEALES, MATRICES')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('CALCULO I', 'CI02', 'ESTE CURSO ENSEÑA SOBRE INTEGRALES Y DERIVADAS')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('CALCULO II', 'CI03', 'ESTE CURSO ENSEÑA SOBRE TRANSFORMACIONES INTEGRALES Y DERIVADAS AVANZADAS')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('PROGRAMACIÓN I', 'CI04', 'ESTE CURSO ENSEÑA SOBRE POO CON EL LENGUAJE JAVA')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('PROGRAMACIÓN II', 'CI05', 'ESTE CURSO ENSEÑA SOBRE POO AVANZADO CON EL LENGUAJE C++')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('PROGRAMACIÓN PARALELA Y CONCURRENTE', 'CI06', 'ESTE CURSO ENSEÑA SOBRE THREADS, FORKS Y CONDICIÓN DE CARRERA')

INSERT INTO CURSO(NOMBRE, SIGLA, DESCRIPCION)
VALUES ('INTRODUCCIÓN A LA COMPUTACIÓN', 'CI07', 'ESTE CURSO ENSEÑA SOBRE HISTORIA DE LA COMPUTACIÓN, ALGORITMIA BÁSICA Y CIRCUITOS')


SELECT * FROM CURSO

