ALTER PROC INSERT_TUTORIA
@FECHAINICIAL AS DATETIME,
@FECHAFINAL AS DATETIME,
@RETRIBUCIONID AS INT,
@TUTOR_CURSOID AS INT,
@ESTADOTUTORIAID AS INT,
@PLATAFORMAID AS INT,
@DETALLESPLATAFORMA VARCHAR(255),
@CARACTERID AS INT,
@MODALIDADID AS INT,
@TIPO_SESIONID AS INT,
@CANTIDADESTUDIANTES AS INT
AS
INSERT INTO TUTORIA(
FechaInicial, 
FechaFinal, 
RetribucionID,
CantidadEstudiantes,
TutorCursoID, 
EstadoTutoriaID, 
PlataformaID, 
DetallesPlataforma, 
CaracterID, 
MODALIDADID, 
TIPO_SESIONID, 
DescripcionRetribucion) 
OUTPUT inserted.*
VALUES (@FECHAINICIAL, @FECHAFINAL, @RETRIBUCIONID, @CANTIDADESTUDIANTES, @TUTOR_CURSOID, @ESTADOTUTORIAID, @PLATAFORMAID, @DETALLESPLATAFORMA, @CARACTERID, @MODALIDADID, @TIPO_SESIONID, NULL);

