ALTER PROC INSERT_TUTORIA_ESTUDIANTE
@TUTORIAID AS INT,
@HORAINGRESO AS DATETIME,
@HORAEGRESO AS DATETIME,
@EVALUACIONID AS INT,
@ESTUDIANTEID AS INT
AS
INSERT INTO TUTORIA_ESTUDIANTE(
TutoriaID, 
HoraIngreso, 
HoraEgreso, 
EvaluacionID, 
EstudianteID) 
OUTPUT inserted.*
VALUES (@TUTORIAID, @HORAINGRESO, @HORAEGRESO, @EVALUACIONID, @ESTUDIANTEID);
