use pi
SELECT * FROM PLATAFORMA

SELECT * FROM USUARIO
SELECT * FROM ESTUDIANTE

exec GET_TUTORIA_POPULATE @ID = 68

SELECT 
TE.HoraIngreso, TE.HoraEgreso, TE.EvaluacionID,
E.ID [EstudianteID],
U.ID [UsuarioID],
U.PrimerNombre,
U.Apellido,
U.Correo,
U.REGION
FROM TUTORIA_ESTUDIANTE TE
JOIN ESTUDIANTE E
ON TE.EstudianteID = E.ID
JOIN USUARIO U
ON E.UsuarioId = U.ID
WHERE TE.TutoriaId = 68

exec GET_TUTORIA_ESTUDIANTE_BY_ID @ID = 68
SELECT * FROM ESTADO_TUTORIA
SELECT * FROM USUARIO
SELECT * FROM ESTUDIANTE
SELECT * FROM TUTORIA_ESTUDIANTE
EXEC GET_ALL_TUTORIAS_THUMBNAIL @ID = 1, @ESTADO = 2

SELECT * FROM USUARIO
SELECT * FROM TUTOR

SELECT * FROM PLATAFORMA
SELECT * FROM PLATAFORMA_TUTOR PT
WHERE PT.tutorID = 8

EXEC GET_PLATAFORMAS_BY_TUTOR_ID @TUTORID = 8

SELECT * FROM TUTORIA
EXEC GET_TUTORIA_POPULATE @ID=79

SELECT * FROM TUTORIA_ESTUDIANTE

select * from PLATAFORMA_TUTOR
INSERT INTO PLATAFORMA_TUTOR(tutorID, plataformaID)
VALUES(21,1)

UPDATE TUTORIA
SET PlataformaID = 2
WHERE ID = 79